- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Download golang Dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go built
  args:
    chdir: /app


- name: Systemd Setup
  ansible.builtin.import_tasks: systemd-setup.yml
