- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Prerequisites
  ansible.builtin.import_tasks:
    file: app-preq.yml

- name: Download Golang Dependencies
  ansible.builtin.shell: go mod init {{component}} ; go get ; go build
  args:
    chdir: /app

- name: Service Setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml